[tool.poetry]
name = "charmcraftcache"
version = "0.1.0"
description = ""
authors = ["Carl Csaposs <carl.csaposs@canonical.com>"]
readme = "README.md"

[tool.poetry.scripts]
ccc = "charmcraftcache.main:app"
charmcraftcache = "charmcraftcache.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
